title: Mehmet Helva, PhD
logo: "/images/pro_pic2.png"
description: Data Scientist and Machine Learning Engineer with a Ph.D. in Physics. Proficient in necessary tools and methods
              eager to apply expertise in data science and ML engineering to deliver data-driven insights and develop
              cutting-edge solutions in a collaborative environment.
              <br><br>
show_downloads: false
theme: jekyll-theme-minimal
