title: Mehmet Helva, PhD
logo: "/images/pro_pic.png"
description: > 
            Data Scientist and Machine Learning Engineer with a Ph.D. in Physics. 
show_downloads: false
theme: jekyll-theme-minimal
